
# Plugin settings
# Important note, the item pattern might not work at the moment, is a later update.
show-inventory-info: true
chat-commands-enabled:
  i: true
  inv: true

debug: true # will not show the NBT data debuger though
use-minecraft-format: true
show-advanced-tooltips: true
